---

# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: lptest003 # gf-rrag-0

services:
  - aiplatform.googleapis.com
  - artifactregistry.googleapis.com
  - bigquery.googleapis.com
  - cloudbuild.googleapis.com
  - cloudresourcemanager.googleapis.com
  - cloudscheduler.googleapis.com
  - run.googleapis.com
  - secretmanager.googleapis.com
  - sqladmin.googleapis.com

service_accounts:
  gf-rrag-fe-0:
  gf-rrag-fe-build-0:
  gf-rrag-ing-0:
  gf-rrag-ing-build-0:
  gf-rrag-ing-sched-0:

iam:
  roles/bigquery.dataViewer:
    - gf-rrag-ing-0
  roles/cloudbuild.builds.editor:
    - gf-rrag-fe-build-0
    - gf-rrag-ing-build-0
  roles/storage.objectCreator:
    - gf-rrag-fe-build-0
    - gf-rrag-ing-build-0
  roles/storage.objectViewer:
    - gf-rrag-fe-build-0
    - gf-rrag-ing-build-0
  roles/artifactregistry.writer:
    - gf-rrag-fe-build-0
    - gf-rrag-ing-build-0
  roles/run.admin:
    - gf-rrag-fe-build-0
    - gf-rrag-ing-build-0
  roles/iam.serviceAccountUser:
    - gf-rrag-fe-build-0
    - gf-rrag-ing-build-0

# roles/aiplatform.user is authoritatively granted
# by aiplatform APIs when activated
iam_bindings_additive:
  - member: gf-rrag-fe-0
    role: roles/aiplatform.user
  - member: gf-rrag-ing-0
    role: roles/aiplatform.user
